name: tg-sum

channels:
  - pytorch

dependencies:
  - python=3.10
  - numpy=1.23.4
  - pandas=1.5.1
  - transformers=4.24.0
  - pytorch=1.13.0
  - datasets
  - sentencepiece=0.1.96
  - pip=22.3.1 
  - pip:
    - origamibot==2.3.2
    - bertopic==0.12.0
